
backend_dependencies: &backend_dependencies
  - 'requirements-*.txt'


migrations_added:
  - added:
      - 'aura/**/migrations/*'

# These files will trigger our workflow to check if lockfile
# updates are needed
migration_lockfile:
  - *backend_dependencies
  - '**/*.py'
