# Generated by Django 5.0.6 on 2024-08-24 14:40

import aura.core.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0001_initial"),
        ("mentalhealth", "0004_alter_disorder_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="call",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="calllog",
            name="call",
        ),
        migrations.RemoveField(
            model_name="calllog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="groupsession",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="groupsessionlog",
            name="group_session",
        ),
        migrations.RemoveField(
            model_name="groupsessionrecording",
            name="group_session",
        ),
        migrations.RemoveField(
            model_name="groupsessionlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notificationsetting",
            name="user",
        ),
        migrations.RemoveField(
            model_name="message",
            name="encrypted_content",
        ),
        migrations.AddField(
            model_name="attachment",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_version",
                to="communication.attachment",
                verbose_name="previous version",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="version_number",
            field=models.PositiveIntegerField(default=1, verbose_name="version number"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=django_cryptography.fields.encrypt(
                models.FileField(
                    upload_to=aura.core.utils.get_upload_path,
                    validators=[
                        django.core.validators.FileExtensionValidator(
                            allowed_extensions=["pdf", "docx", "doc"]
                        )
                    ],
                    verbose_name="file",
                )
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=django_cryptography.fields.encrypt(
                models.TextField(verbose_name="text")
            ),
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="communication.folder",
                        verbose_name="parent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "folder",
                "verbose_name_plural": "folders",
            },
        ),
        migrations.CreateModel(
            name="TherapySessionThread",
            fields=[
                (
                    "thread_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="communication.thread",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread",
                        to="mentalhealth.therapysession",
                        verbose_name="session",
                    ),
                ),
            ],
            options={
                "verbose_name": "therapy session thread",
                "verbose_name_plural": "therapy session threads",
            },
            bases=("communication.thread",),
        ),
        migrations.DeleteModel(
            name="Recording",
        ),
        migrations.DeleteModel(
            name="Call",
        ),
        migrations.DeleteModel(
            name="CallLog",
        ),
        migrations.DeleteModel(
            name="GroupSession",
        ),
        migrations.DeleteModel(
            name="GroupSessionRecording",
        ),
        migrations.DeleteModel(
            name="GroupSessionLog",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="NotificationSetting",
        ),
    ]
