# Generated by Django 5.1.1 on 2025-02-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(verbose_name="text"),
        ),
    ]
