# Generated by Django 5.0.6 on 2024-08-24 16:21

import aura.core.utils
import django.core.validators
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0002_remove_call_participants_remove_calllog_call_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=django_cryptography.fields.encrypt(
                models.FileField(
                    upload_to=aura.core.utils.version_file,
                    validators=[
                        django.core.validators.FileExtensionValidator(
                            allowed_extensions=["pdf", "docx", "doc"]
                        )
                    ],
                    verbose_name="file",
                )
            ),
        ),
    ]
