# Generated by Django 5.0.12 on 2025-03-28 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0003_alter_message_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="uploaded_by",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["thread", "created"], name="communicati_thread__6c441f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["read_at"], name="communicati_read_at_f4cf7e_idx"
            ),
        ),
    ]
