global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
        - prometheus:9090
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080'] # Use the container name and Traefik's API port
