# Generated by Django 5.0.6 on 2024-08-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mentalhealth",
            "0003_alter_disorder_options_remove_disorder_created_and_more",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="disorders",
            field=models.ManyToManyField(
                related_name="patients",
                to="mentalhealth.disorder",
                verbose_name="Disorders",
            ),
        ),
    ]
