# Generated by Django 4.2.13 on 2024-07-07 03:04

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_password_expired_user_last_password_change_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(max_length=120, verbose_name="avatar url"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", " Male"), ("f", "Female")], max_length=1
                    ),
                ),
                ("certification", models.CharField(max_length=100)),
                ("areas_of_expertise", models.CharField(max_length=25)),
                ("coaching_philosophy", models.TextField(blank=True)),
                (
                    "availability",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Availability Schedule"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Rating"
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                (
                    "weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Weight (kg)"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Height (cm)"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Coaches",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(max_length=120, verbose_name="avatar url"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", " Male"), ("f", "Female")], max_length=1
                    ),
                ),
                ("medical_record_number", models.CharField(max_length=100)),
                ("insurance_provider", models.CharField(max_length=100)),
                ("insurance_policy_number", models.CharField(max_length=100)),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_phone", models.CharField(max_length=100)),
                ("allergies", models.TextField()),
                ("medical_conditions", models.TextField()),
                ("medical_history", models.JSONField(blank=True, null=True)),
                ("current_medications", models.JSONField(blank=True, null=True)),
                ("health_data", models.JSONField(blank=True, null=True)),
                ("preferences", models.JSONField(blank=True, null=True)),
                (
                    "weight",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Weight (kg)"
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Height (cm)"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(max_length=120, verbose_name="avatar url"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", " Male"), ("f", "Female")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="Therapist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(max_length=120, verbose_name="avatar url"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Biography")),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", " Male"), ("f", "Female")], max_length=1
                    ),
                ),
                ("license_number", models.CharField(max_length=50)),
                ("specialties", models.CharField(max_length=255)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(verbose_name="Years of Experience"),
                ),
                (
                    "availability",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Availability Schedule"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Therapists",
            },
        ),
        migrations.RemoveField(
            model_name="therapistprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="CoachProfile",
        ),
    ]
