# Generated by Django 5.1.1 on 2025-02-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userip_delete_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userip",
            name="country_code",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="userip",
            name="region_code",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
