# Generated by Django 5.1.1 on 2025-02-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userip_country_code_alter_userip_region_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userip",
            name="country_code",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="userip",
            name="region_code",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
