# Generated by Django 4.2.13 on 2024-07-07 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_delete_patientprofile_delete_therapistprofile_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
