# Generated by Django 5.0.6 on 2024-07-30 19:57

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models

import aura.users.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("users", "0004_physician_review_delete_patientprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_policy_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_record_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="physician",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
