# Generated by Django 4.2.13 on 2024-07-07 03:50

import aura.users.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
