# Generated by Django 5.0.6 on 2024-07-30 20:09

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("users", "0005_remove_patientprofile_user_coach_embedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name="physician",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name="therapist",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddIndex(
            model_name="therapist",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="th_27072024_embedding_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.DeleteModel(
            name="PatientProfile",
        ),
    ]
