# Generated by Django 5.0.6 on 2024-07-26 23:29

import aura.users.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_therapist_th_27072024_embedding_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="physician",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="user",
            field=aura.users.fields.AutoOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
