# Generated by Django 5.0.6 on 2024-08-02 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_patientprofile_user_coach_embedding_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="user",
            new_name="reviewer",
        ),
    ]
