# Generated by Django 4.2.13 on 2024-07-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_coach_user_alter_patient_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
