# Generated by Django 5.1.1 on 2025-02-23 17:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_coach_user_alter_patient_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name="physician",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
