# Generated by Django 4.2.13 on 2024-07-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_coach_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=100, unique=True, verbose_name="email address"
            ),
        ),
    ]
