# Generated by Django 4.2.13 on 2024-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapist",
            name="years_of_experience",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Years of Experience"
            ),
        ),
    ]
