# Generated by Django 4.2.13 on 2024-07-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_therapist_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_policy_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_record_number",
            field=models.CharField(max_length=50),
        ),
    ]
