# Generated by Django 4.2.13 on 2024-07-10 08:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_patient_emergency_contact_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=3,
                verbose_name="Rating",
            ),
        ),
    ]
