# Generated by Django 5.0.6 on 2024-07-26 21:54

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_coach_rating_remove_therapist_specialties_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gps", "Google Play Store"),
                            ("aas", "Apple App Store"),
                            ("web", "Web"),
                            ("email", "Email"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("therapy", "Therapy"),
                            ("psychiatry", "Psychiatry"),
                            ("coaching", "Coaching"),
                            ("mental_health", "Mental Health"),
                            ("wellness", "Wellness"),
                        ],
                        max_length=100,
                    ),
                ),
                ("rating", models.PositiveIntegerField()),
                ("review", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
