# Generated by Django 4.2.13 on 2024-07-11 20:05

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_coach_embedding_patient_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name="physician",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
