# Generated by Django 4.2.13 on 2024-07-06 13:16
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    """ """

    initial = True

    dependencies = [
        ("users",
         "0002_user_is_password_expired_user_last_password_change_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("cardiovascular", "Cardiovascular"),
                            ("diabetes", "Diabetes"),
                            ("mental_health", "Mental Health"),
                        ],
                        help_text="Type of health assessment conducted",
                        max_length=15,
                        verbose_name="Assessment Type",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        help_text="Level of risk identified in the assessment",
                        max_length=8,
                        verbose_name="Risk Level",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        help_text="Recommendations based on the assessment"),
                ),
                (
                    "responses",
                    models.JSONField(
                        help_text="Responses provided during the assessment",
                        verbose_name="Responses",
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        help_text="Result of the health assessment",
                        verbose_name="Result",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True,
                                         verbose_name="Created At"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_assessments",
                        to="users.patientprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Assessment",
                "verbose_name_plural": "Health Assessments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthRiskPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "health_issue",
                    models.CharField(
                        help_text="Specific health issue identified",
                        max_length=255,
                        verbose_name="Health Issue",
                    ),
                ),
                (
                    "preventive_measures",
                    models.TextField(
                        help_text="Measures to prevent the identified health issue",
                        verbose_name="Preventive Measures",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True,
                                         verbose_name="Created At"),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_risk_predictions",
                        to="assessments.healthassessment",
                        verbose_name="Health Assessment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_risk_predictions",
                        to="users.patientprofile",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Risk Prediction",
                "verbose_name_plural": "Health Risk Predictions",
                "ordering": ["created_at"],
            },
        ),
    ]
