# Generated by Django 5.0.6 on 2024-08-28 19:01

import django.core.validators
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields
import pgvector.django
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("cardiovascular", "Cardiovascular"),
                            ("diabetes", "Diabetes"),
                            ("mental_health", "Mental Health"),
                            ("anxiety", "Anxiety"),
                            ("depression", "Depression"),
                            ("bipolar_disorder", "Bipolar Disorder"),
                            ("ocd", "OCD"),
                            ("ptsd", "PTSD"),
                            ("post_partum_depression", "Post-partum Depression"),
                            ("panic_disorder", "Panic Disorder"),
                        ],
                        max_length=50,
                        verbose_name="Assessment Type",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        max_length=8,
                        verbose_name="Risk Level",
                    ),
                ),
                ("recommendations", models.TextField(blank=True)),
                ("result", models.TextField(blank=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024, null=True)),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, unique=True)),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("cardiovascular", "Cardiovascular"),
                            ("diabetes", "Diabetes"),
                            ("mental_health", "Mental Health"),
                            ("anxiety", "Anxiety"),
                            ("depression", "Depression"),
                            ("bipolar_disorder", "Bipolar Disorder"),
                            ("ocd", "OCD"),
                            ("ptsd", "PTSD"),
                            ("post_partum_depression", "Post-partum Depression"),
                            ("panic_disorder", "Panic Disorder"),
                        ],
                        max_length=50,
                        verbose_name="Assessment Type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("answer", models.TextField()),
                ("is_valid", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiskPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("health_issue", models.CharField(max_length=255)),
                ("preventive_measures", models.TextField()),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("source", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
