# Generated by Django 5.0.6 on 2024-08-03 18:40

import django.core.validators
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields
from decimal import Decimal
from django.db import migrations, models

from pgvector.django import VectorField

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                        ],
                        default="draft",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now,
                        monitor="status",
                        verbose_name="status changed",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("cardiovascular", "Cardiovascular"),
                            ("diabetes", "Diabetes"),
                            ("mental_health", "Mental Health"),
                            ("anxiety", "Anxiety"),
                            ("depression", "Depression"),
                            ("bipolar_disorder", "Bipolar Disorder"),
                            ("ocd", "OCD"),
                            ("ptsd", "PTSD"),
                            ("post_partum_depression", "Post-partum Depression"),
                            ("panic_disorder", "Panic Disorder"),
                        ],
                        help_text="Type of health assessment conducted",
                        max_length=50,
                        verbose_name="Assessment Type",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        help_text="Level of risk identified in the assessment",
                        max_length=8,
                        verbose_name="Risk Level",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        help_text="Recommendations based on the assessment"
                    ),
                ),
                (
                    "responses",
                    models.JSONField(
                        help_text="Responses provided during the assessment",
                        verbose_name="Responses",
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        help_text="Result of the health assessment",
                        verbose_name="Result",
                    ),
                ),
                (
                    "embedding",
                    VectorField(dimensions=1024, null=True),
                ),
            ],
            options={
                "verbose_name": "Health Assessment",
                "verbose_name_plural": "Health Assessments",
            },
        ),
        migrations.CreateModel(
            name="HealthAssessmentQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the question in the assessment."
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Assessment Question",
                "verbose_name_plural": "Health Assessment Questions",
            },
        ),
        migrations.CreateModel(
            name="HealthRiskPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "health_issue",
                    models.CharField(
                        help_text="Specific health issue identified",
                        max_length=255,
                        verbose_name="Health Issue",
                    ),
                ),
                (
                    "preventive_measures",
                    models.TextField(
                        help_text="Measures to prevent the identified health issue",
                        verbose_name="Preventive Measures",
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence level of the prediction",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source or method of the prediction", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Risk Prediction",
                "verbose_name_plural": "Health Risk Predictions",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
