# Generated by Django 5.0.6 on 2024-08-28 19:01

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="users.patient",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="assessments.question",
            ),
        ),
        migrations.AddField(
            model_name="riskprediction",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_predictions",
                to="assessments.assessment",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=pgvector.django.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="assessment_embedding_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="response",
            unique_together={("assessment", "question")},
        ),
    ]
