# Generated by Django 4.2.13 on 2024-07-07 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_password_expired_user_last_password_change_and_more"),
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthassessment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="healthassessment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_assessments",
                to="users.patientprofile",
            ),
        ),
        migrations.AlterField(
            model_name="healthriskprediction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
