# Generated by Django 5.0.6 on 2024-08-03 18:40

import django.db.models.deletion
import pgvector.django.indexes
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="healthassessment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_assessments",
                to="users.patient",
            ),
        ),
        migrations.AddField(
            model_name="healthassessmentquestion",
            name="health_assessment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_assessment_questions",
                to="assessments.healthassessment",
                verbose_name="Health Assessment",
            ),
        ),
        migrations.AddField(
            model_name="healthriskprediction",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_risk_predictions",
                to="assessments.healthassessment",
                verbose_name="Health Assessment",
            ),
        ),
        migrations.AddField(
            model_name="healthriskprediction",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_risk_predictions",
                to="users.patient",
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="healthassessmentquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_assessment_questions",
                to="assessments.question",
                verbose_name="Question",
            ),
        ),
        migrations.AddField(
            model_name="healthassessment",
            name="questions",
            field=models.ManyToManyField(
                help_text="Questions in the health assessment",
                related_name="health_assessments",
                through="assessments.HealthAssessmentQuestion",
                to="assessments.question",
                verbose_name="Questions",
            ),
        ),
        migrations.AddIndex(
            model_name="healthassessment",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="ha_27072024_embedding_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
