# Generated by Django 4.2.13 on 2024-07-07 07:09

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0003_alter_healthassessment_patient_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthassessment",
            options={
                "verbose_name": "Health Assessment",
                "verbose_name_plural": "Health Assessments",
            },
        ),
        migrations.AlterModelOptions(
            name="healthriskprediction",
            options={
                "verbose_name": "Health Risk Prediction",
                "verbose_name_plural": "Health Risk Predictions",
            },
        ),
        migrations.RemoveField(
            model_name="healthassessment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="healthriskprediction",
            name="created_at",
        ),
        migrations.AddField(
            model_name="healthassessment",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="healthassessment",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="healthassessment",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("draft", "Draft"),
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="healthassessment",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="status",
                verbose_name="status changed",
            ),
        ),
        migrations.AddField(
            model_name="healthriskprediction",
            name="confidence_level",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Confidence level of the prediction",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="healthriskprediction",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="healthriskprediction",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="healthriskprediction",
            name="source",
            field=models.CharField(
                default="",
                help_text="Source or method of the prediction",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
