# Generated by Django 4.2.13 on 2024-07-07 07:09

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0003_alter_healthassessment_patient_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="healthassessment",
            options={
                "verbose_name": "Health Assessment",
                "verbose_name_plural": "Health Assessments",
            },
        ),
        migrations.AlterModelOptions(
            name="healthriskprediction",
            options={
                "verbose_name": "Health Risk Prediction",
                "verbose_name_plural": "Health Risk Predictions",
            },
        ),
    ]
