# Generated by Django 5.1.1 on 2024-09-12 06:22

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0003_rename_answer_response_content_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("result", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024, null=True)),
            ],
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="assessment",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="assessment",
            name="assessment_embedding_index",
        ),
        migrations.RenameField(
            model_name="response",
            old_name="content",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="embedding",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="recommendations",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="result",
        ),
        migrations.RemoveField(
            model_name="response",
            name="allow_multiple",
        ),
        migrations.AddField(
            model_name="question",
            name="allow_multiple",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="patientassessment",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_assessments",
                to="assessments.assessment",
            ),
        ),
        migrations.AddField(
            model_name="patientassessment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_assessments",
                to="users.patient",
            ),
        ),
        migrations.AlterField(
            model_name="riskprediction",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_predictions",
                to="assessments.patientassessment",
            ),
        ),
        migrations.AddIndex(
            model_name="patientassessment",
            index=pgvector.django.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="pa_embedding_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
