# Generated by Django 5.1.1 on 2024-09-14 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0004_patientassessment_alter_assessment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskprediction",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_predictions",
                to="assessments.patientassessment",
                verbose_name="Patient Assessment",
            ),
        ),
    ]
