# Generated by Django 4.2.13 on 2024-07-11 18:35

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0004_alter_healthassessment_options_and_more"),
    ]

    operations = [
        VectorExtension(),
    ]
