# Generated by Django 5.1.1 on 2025-02-23 17:26

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0005_alter_riskprediction_assessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientassessment",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
