# Generated by Django 4.2.13 on 2024-07-11 18:38

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0005_auto_20240711_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthassessment",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AlterField(
            model_name="healthassessment",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("cardiovascular", "Cardiovascular"),
                    ("diabetes", "Diabetes"),
                    ("mental_health", "Mental Health"),
                    ("anxiety", "Anxiety"),
                    ("depression", "Depression"),
                    ("bipolar_disorder", "Bipolar Disorder"),
                    ("ocd", "OCD"),
                    ("ptsd", "PTSD"),
                    ("post_partum_depression", "Post-partum Depression"),
                    ("panic_disorder", "Panic Disorder"),
                ],
                help_text="Type of health assessment conducted",
                max_length=50,
                verbose_name="Assessment Type",
            ),
        ),
    ]
