# Generated by Django 5.0.6 on 2024-07-30 20:09

import django.core.validators
import django.utils.timezone
import model_utils.fields
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0005_auto_20240711_1835"),
        ("users", "0005_remove_patientprofile_user_coach_embedding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthassessment",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="healthassessment",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name="healthassessment",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="healthassessment",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("draft", "Draft"),
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                ],
                default="draft",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="healthassessment",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now,
                monitor="status",
                verbose_name="status changed",
            ),
        ),
        migrations.AddField(
            model_name="healthriskprediction",
            name="confidence_level",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Confidence level of the prediction",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="healthriskprediction",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="healthriskprediction",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="healthriskprediction",
            name="source",
            field=models.CharField(
                default=1,
                help_text="Source or method of the prediction",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="healthassessment",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("cardiovascular", "Cardiovascular"),
                    ("diabetes", "Diabetes"),
                    ("mental_health", "Mental Health"),
                    ("anxiety", "Anxiety"),
                    ("depression", "Depression"),
                    ("bipolar_disorder", "Bipolar Disorder"),
                    ("ocd", "OCD"),
                    ("ptsd", "PTSD"),
                    ("post_partum_depression", "Post-partum Depression"),
                    ("panic_disorder", "Panic Disorder"),
                ],
                help_text="Type of health assessment conducted",
                max_length=50,
                verbose_name="Assessment Type",
            ),
        ),
        migrations.AddIndex(
            model_name="healthassessment",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="ha_27072024_embedding_index",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
