# Generated by Django 5.0.6 on 2024-07-30 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0006_remove_healthassessment_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthassessment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="healthriskprediction",
            name="created_at",
        ),
    ]
