# Generated by Django 5.1.1 on 2025-03-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0006_alter_patientassessment_embedding"),
        ("users", "0008_alter_coach_embedding_alter_patient_embedding_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="patientassessment",
            index=models.Index(
                fields=["created"], name="assessments_created_a92a0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientassessment",
            index=models.Index(
                fields=["modified"], name="assessments_modifie_5afa0f_idx"
            ),
        ),
    ]
