# Generated by Django 4.2.13 on 2024-07-11 20:05

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0006_healthassessment_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthassessment",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
