#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


# python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.wsgi --workers 4 --thread 2 --worker-class gthread --bind 0.0.0.0:5000 --chdir=/app --reload
