# Generated by Django 5.1.1 on 2025-02-05 05:11

import aura.core.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("authtoken", "0004_alter_tokenproxy_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gps", "Google Play Store"),
                            ("aas", "Apple App Store"),
                            ("web", "Web"),
                            ("email", "Email"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("therapy", "Therapy"),
                            ("psychiatry", "Psychiatry"),
                            ("coaching", "Coaching"),
                            ("mental_health", "Mental Health"),
                            ("wellness", "Wellness"),
                        ],
                        max_length=100,
                    ),
                ),
                ("rating", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("target_object", models.BigIntegerField(null=True)),
                ("event", models.PositiveBigIntegerField()),
                (
                    "ip_address",
                    models.GenericIPAddressField(null=True, unpack_ipv4=True),
                ),
                ("data", aura.core.fields.GzippedDictField()),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "actor_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authtoken.token",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["datetime"], name="core_auditl_datetim_e0e326_idx"
                    ),
                    models.Index(
                        fields=["event", "datetime"],
                        name="core_auditl_event_fe6d39_idx",
                    ),
                ],
            },
        ),
    ]
