# Generated by Django 5.1.1 on 2025-02-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicianReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Last Name"),
                ),
                (
                    "work_email",
                    models.EmailField(max_length=254, verbose_name="Work Email"),
                ),
                (
                    "work_phone_number",
                    models.CharField(max_length=20, verbose_name="Work Phone Number"),
                ),
                (
                    "practice_name",
                    models.CharField(max_length=255, verbose_name="Name of Practice"),
                ),
                (
                    "state_of_practice",
                    models.CharField(
                        max_length=2, verbose_name="State of Practice (2-letter code)"
                    ),
                ),
                (
                    "medical_group_aco",
                    models.CharField(
                        max_length=255, verbose_name="Medical Group / ACO Affiliation"
                    ),
                ),
                (
                    "practice_size",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2-10", "2-10"),
                            ("11-50", "11-50"),
                            ("51-100", "51-100"),
                            ("101-500", "101-500"),
                            ("500+", "500+"),
                        ],
                        max_length=10,
                        verbose_name="Practice Size",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Physician Referral",
                "verbose_name_plural": "Physician Referrals",
            },
        ),
    ]
