# Metricbeat Configuration for Aura System Monitoring
# Collects system and application metrics

# Global settings
name: "aura-metricbeat"
tags: ["aura", "metrics", "monitoring"]

# Metricbeat modules configuration
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

# System module - Basic system metrics
metricbeat.modules:
  # System metrics
  - module: system
    period: 10s
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - socket_summary
      - filesystem
      - fsstat
      - diskio
      - socket
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5
    cpu.metrics: ["percentages", "normalized_percentages"]
    core.metrics: ["percentages"]

  # Docker module - Container metrics
  - module: docker
    period: 10s
    hosts: ["unix:///var/run/docker.sock"]
    metricsets:
      - container
      - cpu
      - diskio
      - event
      - healthcheck
      - info
      - memory
      - network

  # HTTP module - Monitor web endpoints
  - module: http
    period: 30s
    metricsets: ["json"]
    hosts: ["http://django:8000/health/"]
    namespace: "aura_health"
    path: "/"
    method: "GET"

  # PostgreSQL module (if accessible)
  - module: postgresql
    period: 30s
    hosts: ["postgres://aura_user:aura_password@postgres:5432/aura_db?sslmode=disable"]
    metricsets:
      - database
      - bgwriter
      - activity
    enabled: true

  # Redis module (if accessible)
  - module: redis
    period: 30s
    hosts: ["redis:6379"]
    metricsets:
      - info
      - keyspace
    enabled: true

  # Elasticsearch module - Monitor ELK stack itself
  - module: elasticsearch
    period: 30s
    hosts: ["http://elasticsearch:9200"]
    username: "elastic"
    password: "aura_elastic_password_2024"
    metricsets:
      - node
      - node_stats
      - cluster_stats
      - index
      - index_recovery
      - index_summary
      - shard
      - ml_job
    xpack.enabled: true

  # Logstash module
  - module: logstash
    period: 30s
    hosts: ["http://logstash:9600"]
    metricsets:
      - node
      - node_stats
    xpack.enabled: true

  # Kibana module
  - module: kibana
    period: 30s
    hosts: ["http://kibana:5601"]
    username: "elastic"
    password: "aura_elastic_password_2024"
    metricsets:
      - status
      - stats
    xpack.enabled: true

# Processors for metric enrichment
processors:
  # Add hostname
  - add_host_metadata:
      when.not.contains.tags: forwarded

  # Add Docker metadata
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  # Add cloud metadata (if running in cloud)
  - add_cloud_metadata: ~

  # Add Kubernetes metadata (if running in k8s)
  - add_kubernetes_metadata:
      host: ${NODE_NAME}
      matchers:
        - logs_path:
            logs_path: "/var/log/containers/"

  # Add fields for service identification
  - add_fields:
      target: ''
      fields:
        service: aura
        environment: production
        beat_name: metricbeat

  # Drop unnecessary fields
  - drop_fields:
      fields: ["agent.hostname", "agent.id", "ecs.version"]

# Output to Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "aura_elastic_password_2024"
  index: "aura-metrics-%{+yyyy.MM.dd}"
  template.name: "aura-metrics"
  template.pattern: "aura-metrics-*"
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0
    index.codec: best_compression
    index.refresh_interval: "10s"

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat.log
  keepfiles: 7
  permissions: 0644
  rotateeverybytes: 100MB

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "aura_elastic_password_2024"

# Performance settings
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 1s

# HTTP endpoint for health checks
http.enabled: true
http.host: "0.0.0.0"
http.port: 5067

# Path configuration
path.data: /usr/share/metricbeat/data
path.logs: /var/log/metricbeat

# Setup template and dashboards
setup.template.enabled: true
setup.template.name: "aura-metrics"
setup.template.pattern: "aura-metrics-*"
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

# Kibana dashboard setup
setup.dashboards.enabled: true
setup.dashboards.index: "aura-metrics-*"
setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "aura_elastic_password_2024"

# ILM policy
setup.ilm.enabled: true
setup.ilm.rollover_alias: "aura-metrics"
setup.ilm.pattern: "{now/d}-000001"
setup.ilm.policy: "aura-metrics-policy"
