# Generated by Django 5.1.11 on 2025-09-07 08:51

import django.contrib.postgres.fields
import django.utils.timezone
import model_utils.fields
import recurrence.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('message', models.TextField(verbose_name='Message')),
                ('response', models.TextField(verbose_name='Response')),
                ('conversation_log', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None, verbose_name='Conversation Log')),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Chatbot Interaction',
                'verbose_name_plural': 'Chatbot Interactions',
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Disorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('mental', 'Mental'), ('physical', 'Physical'), ('genetic', 'Genetic'), ('emotional', 'Emotional'), ('behavioral', 'Behavioral'), ('functional', 'Functional')], max_length=10, verbose_name='Disorder Type')),
                ('signs_and_symptoms', models.TextField()),
                ('description', models.TextField()),
                ('treatment', models.TextField()),
                ('symptoms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('causes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('prevention', models.TextField()),
            ],
            options={
                'verbose_name': 'Disorder',
                'verbose_name_plural': 'Disorders',
            },
        ),
        migrations.CreateModel(
            name='TherapyApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Therapy Approach',
                'verbose_name_plural': 'Therapy Approaches',
            },
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('session_type', models.CharField(choices=[('chat', 'Chat'), ('video', 'Video'), ('audio', 'Audio')], max_length=5, verbose_name='Session Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(verbose_name='Scheduled At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended At')),
                ('target_audience', models.CharField(choices=[('individual', 'Individual'), ('couples', 'Couples'), ('teens', 'Teens'), ('medication', 'Medication'), ('veterans', 'Veterans')], max_length=10, verbose_name='Target Audience')),
                ('recurrences', recurrence.fields.RecurrenceField()),
            ],
            options={
                'verbose_name': 'Therapy Session',
                'verbose_name_plural': 'Therapy Sessions',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
