# Generated by Django 5.0.6 on 2024-08-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mentalhealth", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatbot_interactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="disorder",
            index=models.Index(
                fields=["name", "type"], name="mentalhealt_name_e630a4_idx"
            ),
        ),
        migrations.AddField(
            model_name="therapysession",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapy_sessions",
                to="users.patient",
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="therapysession",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapy_sessions",
                to="users.therapist",
                verbose_name="Therapist",
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotinteraction",
            index=models.Index(
                fields=["user", "-interaction_date"],
                name="mentalhealt_user_id_b650c1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="therapysession",
            constraint=models.CheckConstraint(
                check=models.Q(("ended_at__gt", models.F("started_at"))),
                name="check_ended_after_started",
            ),
        ),
    ]
