# Generated by Django 4.2.13 on 2024-07-06 12:21
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """ """

    dependencies = [
        ("mentalhealth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbotinteraction",
            name="conversation_log",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatbotinteraction",
            name="interaction_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="therapysession",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="therapysession",
            name="summary",
            field=models.TextField(blank=True),
        ),
    ]
