# Generated by Django 5.0.6 on 2024-08-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentalhealth", "0002_initial"),
    ]

    operations = [
    ]
