# Generated by Django 4.2.13 on 2024-07-07 17:18

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("mentalhealth", "0002_chatbotinteraction_conversation_log_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatbotinteraction",
            options={
                "ordering": ["created"],
                "verbose_name": "Chatbot Interaction",
                "verbose_name_plural": "Chatbot Interactions",
            },
        ),
        migrations.RenameField(
            model_name="chatbotinteraction",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="therapysession",
            old_name="created_at",
            new_name="created",
        ),
        migrations.AddField(
            model_name="chatbotinteraction",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="therapysession",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
    ]
