# Generated by Django 5.0.6 on 2024-08-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentalhealth", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disorder",
            options={
                "verbose_name": "Disorder Type",
                "verbose_name_plural": "Disorder Types",
            },
        ),
        migrations.RemoveField(
            model_name="disorder",
            name="created",
        ),
        migrations.RemoveField(
            model_name="disorder",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="disorder",
            name="modified",
        ),
        migrations.AddField(
            model_name="disorder",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disorder",
            name="signs_and_symptoms",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="disorder",
            name="causes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="disorder",
            name="prevention",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="disorder",
            name="symptoms",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="disorder",
            name="treatment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="disorder",
            name="type",
            field=models.CharField(
                choices=[
                    ("mental", "Mental"),
                    ("physical", "Physical"),
                    ("genetic", "Genetic"),
                    ("emotional", "Emotional"),
                    ("behavioral", "Behavioral"),
                    ("functional", "Functional"),
                ],
                max_length=10,
                verbose_name="Disorder Type",
            ),
        ),
    ]
