# Generated by Django 4.2.13 on 2024-07-10 07:28

import recurrence.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mentalhealth", "0003_alter_chatbotinteraction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapysession",
            name="recurrences",
            field=recurrence.fields.RecurrenceField(default=""),
            preserve_default=False,
        ),
    ]
