# Generated by Django 5.1.1 on 2025-02-05 08:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentalhealth", "0003_alter_therapysession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disorder",
            name="causes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="disorder",
            name="symptoms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
