# Generated by Django 5.0.6 on 2024-08-23 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "mentalhealth",
            "0003_alter_disorder_options_remove_disorder_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disorder",
            options={},
        ),
    ]
