# Generated by Django 5.0.6 on 2024-07-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentalhealth", "0004_therapysession_recurrences"),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapyApproach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Therapy Approach",
                "verbose_name_plural": "Therapy Approaches",
            },
        ),
    ]
