# Generated by Django 4.2.13 on 2024-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mentalhealth", "0004_therapysession_recurrences"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapysession",
            name="traget_audience",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("couples", "Couples"),
                    ("teens", "Teens"),
                    ("medication", "Medication"),
                    ("veterans", "Veterans"),
                ],
                default="individual",
                max_length=10,
                verbose_name="Session Type",
            ),
            preserve_default=False,
        ),
    ]
