# Generated by Django 5.0.6 on 2024-07-30 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mentalhealth", "0005_therapyapproach"),
    ]

    operations = [
        migrations.RenameField(
            model_name="therapysession",
            old_name="traget_audience",
            new_name="target_audience",
        ),
    ]
