# Generated by Django 5.1.1 on 2025-06-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mentalhealth", "0005_therapysession_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="therapysession",
            name="check_ended_after_started",
        ),
    ]
