# Generated by Django 5.0.6 on 2024-08-02 16:52

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mentalhealth", "0006_rename_traget_audience_therapysession_target_audience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapysession",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
    ]
